// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Footer → our_services*
 */
export interface FooterDocumentDataOurServicesItem {
  /**
   * service_name field in *Footer → our_services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.our_services[].service_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  service_name: prismic.KeyTextField;

  /**
   * service_link field in *Footer → our_services*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.our_services[].service_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  service_link: prismic.LinkField;
}

/**
 * Item in *Footer → social_media_list*
 */
export interface FooterDocumentDataSocialMediaListItem {
  /**
   * social_media_logo field in *Footer → social_media_list*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media_list[].social_media_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  social_media_logo: prismic.ImageField<never>;

  /**
   * social_media_link field in *Footer → social_media_list*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media_list[].social_media_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_media_link: prismic.LinkField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * contact_title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contact_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_title: prismic.KeyTextField;

  /**
   * company_name_eng field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.company_name_eng
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name_eng: prismic.KeyTextField;

  /**
   * company_name_thai field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.company_name_thai
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name_thai: prismic.KeyTextField;

  /**
   * company_address field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.company_address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_address: prismic.KeyTextField;

  /**
   * email field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * telephone field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.telephone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  telephone: prismic.KeyTextField;

  /**
   * fax field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.fax
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  fax: prismic.KeyTextField;

  /**
   * our_services field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.our_services[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  our_services: prismic.GroupField<Simplify<FooterDocumentDataOurServicesItem>>;

  /**
   * subscribe_name field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.subscribe_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subscribe_name: prismic.KeyTextField;

  /**
   * subscribe_placeholder field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.subscribe_placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subscribe_placeholder: prismic.KeyTextField;

  /**
   * subscribe_button_name field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.subscribe_button_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subscribe_button_name: prismic.KeyTextField;

  /**
   * subscribe_button_link field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.subscribe_button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subscribe_button_link: prismic.KeyTextField;

  /**
   * social_media_list field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media_list[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_media_list: prismic.GroupField<
    Simplify<FooterDocumentDataSocialMediaListItem>
  >;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;

type HomeDocumentDataSlicesSlice =
  | BannerSectionSlice
  | BackgroundColorWithButtonLinkSlice
  | ImageIconWithContentBottomSlice
  | OpportunityListSlice
  | TraningCourseListSlice
  | TraningCourseSlice
  | TrainingAwardSlice
  | PromotionAndPrivilegeSlice
  | HaveAProblemSlice
  | CallToActionWithBannerSlice;

/**
 * Content for Home Page documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.TitleField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | HeroSlice
  | QuoteSlice
  | TextSlice
  | ImageSlice
  | ImageCardsSlice
  | TextWithImageSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Parent field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.ContentRelationshipField<"page">;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  siteTitle: prismic.TitleField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | HomeDocument
  | NavigationDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *BackgroundColorWithButtonLink → Primary*
 */
export interface BackgroundColorWithButtonLinkSliceDefaultPrimary {
  /**
   * is_active field in *BackgroundColorWithButtonLink → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: background_color_with_button_link.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Primary content in *BackgroundColorWithButtonLink → Items*
 */
export interface BackgroundColorWithButtonLinkSliceDefaultItem {
  /**
   * button_title field in *BackgroundColorWithButtonLink → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: background_color_with_button_link.items[].button_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_title: prismic.KeyTextField;

  /**
   * button_description field in *BackgroundColorWithButtonLink → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: background_color_with_button_link.items[].button_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  button_description: prismic.RichTextField;

  /**
   * button_link field in *BackgroundColorWithButtonLink → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: background_color_with_button_link.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * button_color field in *BackgroundColorWithButtonLink → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: background_color_with_button_link.items[].button_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_color: prismic.ColorField;
}

/**
 * Default variation for BackgroundColorWithButtonLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BackgroundColorWithButtonLinkSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<BackgroundColorWithButtonLinkSliceDefaultPrimary>,
    Simplify<BackgroundColorWithButtonLinkSliceDefaultItem>
  >;

/**
 * Slice variation for *BackgroundColorWithButtonLink*
 */
type BackgroundColorWithButtonLinkSliceVariation =
  BackgroundColorWithButtonLinkSliceDefault;

/**
 * BackgroundColorWithButtonLink Shared Slice
 *
 * - **API ID**: `background_color_with_button_link`
 * - **Description**: BackgroundColorWithButtonLink
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BackgroundColorWithButtonLinkSlice = prismic.SharedSlice<
  "background_color_with_button_link",
  BackgroundColorWithButtonLinkSliceVariation
>;

/**
 * Primary content in *BannerSection → Primary*
 */
export interface BannerSectionSliceDefaultPrimary {
  /**
   * image_desktop field in *BannerSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_section.primary.image_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_desktop: prismic.ImageField<never>;

  /**
   * image_mobile field in *BannerSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_section.primary.image_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_mobile: prismic.ImageField<never>;

  /**
   * is_active field in *BannerSection → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: banner_section.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Default variation for BannerSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BannerSection*
 */
type BannerSectionSliceVariation = BannerSectionSliceDefault;

/**
 * BannerSection Shared Slice
 *
 * - **API ID**: `banner_section`
 * - **Description**: BannerSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSectionSlice = prismic.SharedSlice<
  "banner_section",
  BannerSectionSliceVariation
>;

/**
 * Primary content in *CallToActionWithBanner → Primary*
 */
export interface CallToActionWithBannerSliceDefaultPrimary {
  /**
   * title field in *CallToActionWithBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_with_banner.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * image_background_desktop field in *CallToActionWithBanner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_with_banner.primary.image_background_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_background_desktop: prismic.ImageField<never>;

  /**
   * image_background_mobile field in *CallToActionWithBanner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_with_banner.primary.image_background_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_background_mobile: prismic.ImageField<never>;

  /**
   * button_name field in *CallToActionWithBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_with_banner.primary.button_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_name: prismic.KeyTextField;

  /**
   * button_link field in *CallToActionWithBanner → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_with_banner.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for CallToActionWithBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionWithBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionWithBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallToActionWithBanner*
 */
type CallToActionWithBannerSliceVariation = CallToActionWithBannerSliceDefault;

/**
 * CallToActionWithBanner Shared Slice
 *
 * - **API ID**: `call_to_action_with_banner`
 * - **Description**: CallToActionWithBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionWithBannerSlice = prismic.SharedSlice<
  "call_to_action_with_banner",
  CallToActionWithBannerSliceVariation
>;

/**
 * Primary content in *HaveAProblem → Primary*
 */
export interface HaveAProblemSliceDefaultPrimary {
  /**
   * have_a_problem_title field in *HaveAProblem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: have_a_problem.primary.have_a_problem_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  have_a_problem_title: prismic.KeyTextField;

  /**
   * have_a_problem_image_desktop field in *HaveAProblem → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: have_a_problem.primary.have_a_problem_image_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  have_a_problem_image_desktop: prismic.ImageField<never>;

  /**
   * have_a_problem_image_mobile field in *HaveAProblem → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: have_a_problem.primary.have_a_problem_image_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  have_a_problem_image_mobile: prismic.ImageField<never>;

  /**
   * is_active field in *HaveAProblem → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: have_a_problem.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Primary content in *HaveAProblem → Items*
 */
export interface HaveAProblemSliceDefaultItem {
  /**
   * have_a_problem_image_icon field in *HaveAProblem → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: have_a_problem.items[].have_a_problem_image_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  have_a_problem_image_icon: prismic.ImageField<never>;

  /**
   * have_a_problem_description field in *HaveAProblem → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: have_a_problem.items[].have_a_problem_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  have_a_problem_description: prismic.RichTextField;
}

/**
 * Default variation for HaveAProblem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HaveAProblemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HaveAProblemSliceDefaultPrimary>,
  Simplify<HaveAProblemSliceDefaultItem>
>;

/**
 * Slice variation for *HaveAProblem*
 */
type HaveAProblemSliceVariation = HaveAProblemSliceDefault;

/**
 * HaveAProblem Shared Slice
 *
 * - **API ID**: `have_a_problem`
 * - **Description**: HaveAProblem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HaveAProblemSlice = prismic.SharedSlice<
  "have_a_problem",
  HaveAProblemSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Text field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * Button Text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Background Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  backgroundImage: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Image → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Image field in *Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Image → Primary*
 */
export interface ImageSliceBannerPrimary {
  /**
   * Image field in *Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Banner variation for Image Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceBanner = prismic.SharedSliceVariation<
  "banner",
  Simplify<ImageSliceBannerPrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault | ImageSliceBanner;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Primary content in *ImageCards → Primary*
 */
export interface ImageCardsSliceDefaultPrimary {
  /**
   * Heading field in *ImageCards → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *ImageCards → Items*
 */
export interface ImageCardsSliceDefaultItem {
  /**
   * Image field in *ImageCards → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *ImageCards → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Button Link field in *ImageCards → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * Button Text field in *ImageCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_cards.items[].buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;
}

/**
 * Default variation for ImageCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageCardsSliceDefaultPrimary>,
  Simplify<ImageCardsSliceDefaultItem>
>;

/**
 * Slice variation for *ImageCards*
 */
type ImageCardsSliceVariation = ImageCardsSliceDefault;

/**
 * ImageCards Shared Slice
 *
 * - **API ID**: `image_cards`
 * - **Description**: ImageCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageCardsSlice = prismic.SharedSlice<
  "image_cards",
  ImageCardsSliceVariation
>;

/**
 * Primary content in *ImageIconWithContentBottom → Primary*
 */
export interface ImageIconWithContentBottomSliceDefaultPrimary {
  /**
   * button_name field in *ImageIconWithContentBottom → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_icon_with_content_bottom.primary.button_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_name: prismic.KeyTextField;

  /**
   * is_active field in *ImageIconWithContentBottom → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image_icon_with_content_bottom.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;

  /**
   * button_link field in *ImageIconWithContentBottom → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_icon_with_content_bottom.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Primary content in *ImageIconWithContentBottom → Items*
 */
export interface ImageIconWithContentBottomSliceDefaultItem {
  /**
   * image_icon field in *ImageIconWithContentBottom → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_icon_with_content_bottom.items[].image_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_icon: prismic.ImageField<never>;

  /**
   * content_subject field in *ImageIconWithContentBottom → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_icon_with_content_bottom.items[].content_subject
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content_subject: prismic.RichTextField;
}

/**
 * Default variation for ImageIconWithContentBottom Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageIconWithContentBottomSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<ImageIconWithContentBottomSliceDefaultPrimary>,
    Simplify<ImageIconWithContentBottomSliceDefaultItem>
  >;

/**
 * Slice variation for *ImageIconWithContentBottom*
 */
type ImageIconWithContentBottomSliceVariation =
  ImageIconWithContentBottomSliceDefault;

/**
 * ImageIconWithContentBottom Shared Slice
 *
 * - **API ID**: `image_icon_with_content_bottom`
 * - **Description**: ImageIconWithContentBottom
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageIconWithContentBottomSlice = prismic.SharedSlice<
  "image_icon_with_content_bottom",
  ImageIconWithContentBottomSliceVariation
>;

/**
 * Primary content in *OpportunityList → Primary*
 */
export interface OpportunityListSliceDefaultPrimary {
  /**
   * opportunity_image_desktop field in *OpportunityList → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunity_list.primary.opportunity_image_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  opportunity_image_desktop: prismic.ImageField<never>;

  /**
   * opportunity_image_mobile field in *OpportunityList → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunity_list.primary.opportunity_image_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  opportunity_image_mobile: prismic.ImageField<never>;

  /**
   * oppportunity_title field in *OpportunityList → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunity_list.primary.oppportunity_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  oppportunity_title: prismic.RichTextField;

  /**
   * is_active field in *OpportunityList → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: opportunity_list.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Primary content in *OpportunityList → Items*
 */
export interface OpportunityListSliceDefaultItem {
  /**
   * opportunity_list_name field in *OpportunityList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunity_list.items[].opportunity_list_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  opportunity_list_name: prismic.KeyTextField;
}

/**
 * Default variation for OpportunityList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OpportunityListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OpportunityListSliceDefaultPrimary>,
  Simplify<OpportunityListSliceDefaultItem>
>;

/**
 * Slice variation for *OpportunityList*
 */
type OpportunityListSliceVariation = OpportunityListSliceDefault;

/**
 * OpportunityList Shared Slice
 *
 * - **API ID**: `opportunity_list`
 * - **Description**: OpportunityList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OpportunityListSlice = prismic.SharedSlice<
  "opportunity_list",
  OpportunityListSliceVariation
>;

/**
 * Primary content in *PromotionAndPrivilege → Primary*
 */
export interface PromotionAndPrivilegeSliceDefaultPrimary {
  /**
   * promotion_and_privilege_title field in *PromotionAndPrivilege → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promotion_and_privilege.primary.promotion_and_privilege_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  promotion_and_privilege_title: prismic.RichTextField;

  /**
   * is_active field in *PromotionAndPrivilege → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: promotion_and_privilege.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Primary content in *PromotionAndPrivilege → Items*
 */
export interface PromotionAndPrivilegeSliceDefaultItem {
  /**
   * promotion_and_privilege_desc field in *PromotionAndPrivilege → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promotion_and_privilege.items[].promotion_and_privilege_desc
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  promotion_and_privilege_desc: prismic.RichTextField;
}

/**
 * Default variation for PromotionAndPrivilege Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PromotionAndPrivilegeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PromotionAndPrivilegeSliceDefaultPrimary>,
  Simplify<PromotionAndPrivilegeSliceDefaultItem>
>;

/**
 * Slice variation for *PromotionAndPrivilege*
 */
type PromotionAndPrivilegeSliceVariation = PromotionAndPrivilegeSliceDefault;

/**
 * PromotionAndPrivilege Shared Slice
 *
 * - **API ID**: `promotion_and_privilege`
 * - **Description**: PromotionAndPrivilege
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PromotionAndPrivilegeSlice = prismic.SharedSlice<
  "promotion_and_privilege",
  PromotionAndPrivilegeSliceVariation
>;

/**
 * Primary content in *Quote → Primary*
 */
export interface QuoteSliceDefaultPrimary {
  /**
   * Quote field in *Quote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;

  /**
   * Source field in *Quote → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.primary.source
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  source: prismic.KeyTextField;
}

/**
 * Default variation for Quote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuoteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Quote*
 */
type QuoteSliceVariation = QuoteSliceDefault;

/**
 * Quote Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSlice = prismic.SharedSlice<"quote", QuoteSliceVariation>;

/**
 * Primary content in *Text → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Text field in *Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Text → Primary*
 */
export interface TextSliceTwoColumnsPrimary {
  /**
   * Text field in *Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Two Columns variation for Text Slice
 *
 * - **API ID**: `twoColumns`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceTwoColumns = prismic.SharedSliceVariation<
  "twoColumns",
  Simplify<TextSliceTwoColumnsPrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault | TextSliceTwoColumns;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

/**
 * Primary content in *TextWithImage → Primary*
 */
export interface TextWithImageSliceDefaultPrimary {
  /**
   * Text field in *TextWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *TextWithImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TextWithImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextWithImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextWithImage → Primary*
 */
export interface TextWithImageSliceWithButtonPrimary {
  /**
   * Text field in *TextWithImage → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Button Link field in *TextWithImage → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonLink: prismic.LinkField;

  /**
   * Button Text field in *TextWithImage → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Image field in *TextWithImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_with_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * With Button variation for TextWithImage Slice
 *
 * - **API ID**: `withButton`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSliceWithButton = prismic.SharedSliceVariation<
  "withButton",
  Simplify<TextWithImageSliceWithButtonPrimary>,
  never
>;

/**
 * Slice variation for *TextWithImage*
 */
type TextWithImageSliceVariation =
  | TextWithImageSliceDefault
  | TextWithImageSliceWithButton;

/**
 * TextWithImage Shared Slice
 *
 * - **API ID**: `text_with_image`
 * - **Description**: TextWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextWithImageSlice = prismic.SharedSlice<
  "text_with_image",
  TextWithImageSliceVariation
>;

/**
 * Primary content in *TrainingAward → Primary*
 */
export interface TrainingAwardSliceDefaultPrimary {
  /**
   * training_award_title field in *TrainingAward → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: training_award.primary.training_award_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  training_award_title: prismic.KeyTextField;

  /**
   * training_award_subtitle field in *TrainingAward → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: training_award.primary.training_award_subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  training_award_subtitle: prismic.RichTextField;

  /**
   * is_active field in *TrainingAward → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: training_award.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Primary content in *TrainingAward → Items*
 */
export interface TrainingAwardSliceDefaultItem {
  /**
   * training_award_step field in *TrainingAward → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: training_award.items[].training_award_step
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  training_award_step: prismic.KeyTextField;

  /**
   * training_award_step_detail field in *TrainingAward → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: training_award.items[].training_award_step_detail
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  training_award_step_detail: prismic.KeyTextField;
}

/**
 * Default variation for TrainingAward Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TrainingAwardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TrainingAwardSliceDefaultPrimary>,
  Simplify<TrainingAwardSliceDefaultItem>
>;

/**
 * Slice variation for *TrainingAward*
 */
type TrainingAwardSliceVariation = TrainingAwardSliceDefault;

/**
 * TrainingAward Shared Slice
 *
 * - **API ID**: `training_award`
 * - **Description**: TrainingAward
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TrainingAwardSlice = prismic.SharedSlice<
  "training_award",
  TrainingAwardSliceVariation
>;

/**
 * Primary content in *TraningCourseCard → Primary*
 */
export interface TraningCourseSliceDefaultPrimary {
  /**
   * title_course field in *TraningCourseCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course.primary.title_course
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_course: prismic.KeyTextField;

  /**
   * subtitle_course field in *TraningCourseCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course.primary.subtitle_course
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle_course: prismic.KeyTextField;

  /**
   * button_all_name_course field in *TraningCourseCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course.primary.button_all_name_course
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_all_name_course: prismic.KeyTextField;

  /**
   * button_all_link_course field in *TraningCourseCard → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course.primary.button_all_link_course
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_all_link_course: prismic.LinkField;

  /**
   * is_active field in *TraningCourseCard → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: traning_course.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Primary content in *TraningCourseCard → Items*
 */
export interface TraningCourseSliceDefaultItem {
  /**
   * course_name field in *TraningCourseCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title Course
   * - **API ID Path**: traning_course.items[].course_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  course_name: prismic.KeyTextField;

  /**
   * course_description field in *TraningCourseCard → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description Course
   * - **API ID Path**: traning_course.items[].course_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  course_description: prismic.RichTextField;

  /**
   * course_image_icon field in *TraningCourseCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course.items[].course_image_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  course_image_icon: prismic.ImageField<never>;

  /**
   * course_button_name field in *TraningCourseCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Button name
   * - **API ID Path**: traning_course.items[].course_button_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  course_button_name: prismic.KeyTextField;

  /**
   * course_button_link field in *TraningCourseCard → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Button Link
   * - **API ID Path**: traning_course.items[].course_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  course_button_link: prismic.LinkField;
}

/**
 * Default variation for TraningCourseCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TraningCourseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TraningCourseSliceDefaultPrimary>,
  Simplify<TraningCourseSliceDefaultItem>
>;

/**
 * Slice variation for *TraningCourseCard*
 */
type TraningCourseSliceVariation = TraningCourseSliceDefault;

/**
 * TraningCourseCard Shared Slice
 *
 * - **API ID**: `traning_course`
 * - **Description**: TraningCourse
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TraningCourseSlice = prismic.SharedSlice<
  "traning_course",
  TraningCourseSliceVariation
>;

/**
 * Primary content in *TraningCourseList → Primary*
 */
export interface TraningCourseListSliceDefaultPrimary {
  /**
   * title_course field in *TraningCourseList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course_list.primary.title_course
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_course: prismic.KeyTextField;

  /**
   * subtitle_course field in *TraningCourseList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course_list.primary.subtitle_course
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle_course: prismic.KeyTextField;

  /**
   * is_active field in *TraningCourseList → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: traning_course_list.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Primary content in *TraningCourseList → Items*
 */
export interface TraningCourseListSliceDefaultItem {
  /**
   * course_name field in *TraningCourseList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course_list.items[].course_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  course_name: prismic.KeyTextField;

  /**
   * course_description field in *TraningCourseList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course_list.items[].course_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  course_description: prismic.KeyTextField;

  /**
   * course_sub_description field in *TraningCourseList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course_list.items[].course_sub_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  course_sub_description: prismic.KeyTextField;

  /**
   * course_button_name field in *TraningCourseList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course_list.items[].course_button_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  course_button_name: prismic.KeyTextField;

  /**
   * course_button_link field in *TraningCourseList → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course_list.items[].course_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  course_button_link: prismic.LinkField;
}

/**
 * Default variation for TraningCourseList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TraningCourseListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TraningCourseListSliceDefaultPrimary>,
  Simplify<TraningCourseListSliceDefaultItem>
>;

/**
 * Slice variation for *TraningCourseList*
 */
type TraningCourseListSliceVariation = TraningCourseListSliceDefault;

/**
 * TraningCourseList Shared Slice
 *
 * - **API ID**: `traning_course_list`
 * - **Description**: TraningCourseList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TraningCourseListSlice = prismic.SharedSlice<
  "traning_course_list",
  TraningCourseListSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataOurServicesItem,
      FooterDocumentDataSocialMediaListItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      BackgroundColorWithButtonLinkSlice,
      BackgroundColorWithButtonLinkSliceDefaultPrimary,
      BackgroundColorWithButtonLinkSliceDefaultItem,
      BackgroundColorWithButtonLinkSliceVariation,
      BackgroundColorWithButtonLinkSliceDefault,
      BannerSectionSlice,
      BannerSectionSliceDefaultPrimary,
      BannerSectionSliceVariation,
      BannerSectionSliceDefault,
      CallToActionWithBannerSlice,
      CallToActionWithBannerSliceDefaultPrimary,
      CallToActionWithBannerSliceVariation,
      CallToActionWithBannerSliceDefault,
      HaveAProblemSlice,
      HaveAProblemSliceDefaultPrimary,
      HaveAProblemSliceDefaultItem,
      HaveAProblemSliceVariation,
      HaveAProblemSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceBannerPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      ImageSliceBanner,
      ImageCardsSlice,
      ImageCardsSliceDefaultPrimary,
      ImageCardsSliceDefaultItem,
      ImageCardsSliceVariation,
      ImageCardsSliceDefault,
      ImageIconWithContentBottomSlice,
      ImageIconWithContentBottomSliceDefaultPrimary,
      ImageIconWithContentBottomSliceDefaultItem,
      ImageIconWithContentBottomSliceVariation,
      ImageIconWithContentBottomSliceDefault,
      OpportunityListSlice,
      OpportunityListSliceDefaultPrimary,
      OpportunityListSliceDefaultItem,
      OpportunityListSliceVariation,
      OpportunityListSliceDefault,
      PromotionAndPrivilegeSlice,
      PromotionAndPrivilegeSliceDefaultPrimary,
      PromotionAndPrivilegeSliceDefaultItem,
      PromotionAndPrivilegeSliceVariation,
      PromotionAndPrivilegeSliceDefault,
      QuoteSlice,
      QuoteSliceDefaultPrimary,
      QuoteSliceVariation,
      QuoteSliceDefault,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceTwoColumnsPrimary,
      TextSliceVariation,
      TextSliceDefault,
      TextSliceTwoColumns,
      TextWithImageSlice,
      TextWithImageSliceDefaultPrimary,
      TextWithImageSliceWithButtonPrimary,
      TextWithImageSliceVariation,
      TextWithImageSliceDefault,
      TextWithImageSliceWithButton,
      TrainingAwardSlice,
      TrainingAwardSliceDefaultPrimary,
      TrainingAwardSliceDefaultItem,
      TrainingAwardSliceVariation,
      TrainingAwardSliceDefault,
      TraningCourseSlice,
      TraningCourseSliceDefaultPrimary,
      TraningCourseSliceDefaultItem,
      TraningCourseSliceVariation,
      TraningCourseSliceDefault,
      TraningCourseListSlice,
      TraningCourseListSliceDefaultPrimary,
      TraningCourseListSliceDefaultItem,
      TraningCourseListSliceVariation,
      TraningCourseListSliceDefault,
    };
  }
}
