// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutUsDocumentDataSlicesSlice =
  | HeroSlice
  | FeeSlice
  | ExperienceSlice
  | TraningCourseListSlice
  | TraningCourseSlice
  | PortfolioSlice
  | PromotionAndPrivilegeSlice
  | TrainingAwardSlice
  | SpeakerWithContentSlice
  | OpportunityListSlice
  | IntroductionSlice
  | ImageIconWithContentBottomSlice
  | ImageContentSlice
  | ImageAndContentSideBySideSlice
  | CallToActionWithBannerSlice
  | BannerSectionSlice
  | BackgroundColorWithButtonLinkSlice;

/**
 * Content for About us documents
 */
interface AboutUsDocumentData {
  /**
   * Slice Zone field in *About us*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutUsDocumentDataSlicesSlice> /**
   * Meta Description field in *About us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about_us.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About us*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *About us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about_us.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * About us document from Prismic
 *
 * - **API ID**: `about_us`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutUsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AboutUsDocumentData>,
    "about_us",
    Lang
  >;

type CurriculumDocumentDataSlicesSlice =
  | FeeSlice
  | ImageContentSlice
  | IntroductionSlice
  | ImageAndContentSideBySideSlice
  | SpeakerSlice;

/**
 * Content for Curriculum documents
 */
interface CurriculumDocumentData {
  /**
   * theme_page field in *Curriculum*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: curriculum.theme_page
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  theme_page: prismic.ColorField;

  /**
   * title field in *Curriculum*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: curriculum.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *Curriculum*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: curriculum.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Slice Zone field in *Curriculum*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: curriculum.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CurriculumDocumentDataSlicesSlice> /**
   * Meta Description field in *Curriculum*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: curriculum.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Curriculum*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: curriculum.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Curriculum*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: curriculum.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Curriculum document from Prismic
 *
 * - **API ID**: `curriculum`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CurriculumDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CurriculumDocumentData>,
    "curriculum",
    Lang
  >;

type ELearningDocumentDataSlicesSlice =
  | TraningCourseListSlice
  | PromotionAndPrivilegeSlice
  | SpeakerSlice
  | SpeakerWithContentSlice
  | TrainingAwardSlice
  | HeroSlice
  | IntroductionSlice
  | TraningCourseSlice
  | ImageAndContentSideBySideSlice
  | ExperienceSlice
  | PortfolioSlice
  | OpportunityListSlice
  | BannerSectionSlice
  | ImageIconWithContentBottomSlice
  | HaveAProblemSlice
  | FeeSlice
  | FaqSlice
  | BackgroundColorWithButtonLinkSlice
  | CallToActionWithBannerSlice
  | ImageContentSlice;

/**
 * Content for E-Learning documents
 */
interface ELearningDocumentData {
  /**
   * Slice Zone field in *E-Learning*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: e_learning.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ELearningDocumentDataSlicesSlice> /**
   * Meta Description field in *E-Learning*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: e_learning.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *E-Learning*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: e_learning.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *E-Learning*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: e_learning.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * E-Learning document from Prismic
 *
 * - **API ID**: `e_learning`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ELearningDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ELearningDocumentData>,
    "e_learning",
    Lang
  >;

/**
 * Item in *Footer → our_services*
 */
export interface FooterDocumentDataOurServicesItem {
  /**
   * service_name field in *Footer → our_services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.our_services[].service_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  service_name: prismic.KeyTextField;

  /**
   * service_link field in *Footer → our_services*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.our_services[].service_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  service_link: prismic.LinkField;
}

/**
 * Item in *Footer → social_media_list*
 */
export interface FooterDocumentDataSocialMediaListItem {
  /**
   * social_media_logo field in *Footer → social_media_list*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media_list[].social_media_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  social_media_logo: prismic.ImageField<never>;

  /**
   * social_media_link field in *Footer → social_media_list*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media_list[].social_media_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_media_link: prismic.LinkField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * image_logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.image_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_logo: prismic.ImageField<never>;

  /**
   * contact_title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contact_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_title: prismic.KeyTextField;

  /**
   * company_name_eng field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.company_name_eng
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name_eng: prismic.KeyTextField;

  /**
   * company_name_thai field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.company_name_thai
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name_thai: prismic.KeyTextField;

  /**
   * company_address field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.company_address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_address: prismic.KeyTextField;

  /**
   * email field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * telephone field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.telephone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  telephone: prismic.KeyTextField;

  /**
   * fax field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.fax
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  fax: prismic.KeyTextField;

  /**
   * our_services field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.our_services[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  our_services: prismic.GroupField<Simplify<FooterDocumentDataOurServicesItem>>;

  /**
   * subscribe_name field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.subscribe_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subscribe_name: prismic.KeyTextField;

  /**
   * subscribe_placeholder field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.subscribe_placeholder
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subscribe_placeholder: prismic.KeyTextField;

  /**
   * subscribe_button_name field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.subscribe_button_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subscribe_button_name: prismic.KeyTextField;

  /**
   * subscribe_button_link field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.subscribe_button_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subscribe_button_link: prismic.KeyTextField;

  /**
   * social_media_list field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media_list[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_media_list: prismic.GroupField<
    Simplify<FooterDocumentDataSocialMediaListItem>
  >;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;

type HomeDocumentDataSlicesSlice =
  | ImageContentSlice
  | PortfolioSlice
  | FaqSlice
  | ExperienceSlice
  | HeroSlice
  | BannerSectionSlice
  | BackgroundColorWithButtonLinkSlice
  | ImageIconWithContentBottomSlice
  | OpportunityListSlice
  | TraningCourseListSlice
  | TraningCourseSlice
  | TrainingAwardSlice
  | PromotionAndPrivilegeSlice
  | HaveAProblemSlice
  | CallToActionWithBannerSlice;

/**
 * Content for Home Page documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *Menu → group_menu*
 */
export interface MenuDocumentDataGroupMenuItem {
  /**
   * submenu_name field in *Menu → group_menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.group_menu[].submenu_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  submenu_name: prismic.KeyTextField;

  /**
   * submenu_link field in *Menu → group_menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.group_menu[].submenu_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  submenu_link: prismic.LinkField;
}

/**
 * Item in *Menu → group_menu2*
 */
export interface MenuDocumentDataGroupMenu2Item {
  /**
   * submenu_name field in *Menu → group_menu2*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.group_menu2[].submenu_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  submenu_name: prismic.KeyTextField;

  /**
   * submenu_link field in *Menu → group_menu2*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.group_menu2[].submenu_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  submenu_link: prismic.LinkField;
}

/**
 * Item in *Menu → group_menu3*
 */
export interface MenuDocumentDataGroupMenu3Item {
  /**
   * submenu_name field in *Menu → group_menu3*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.group_menu3[].submenu_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  submenu_name: prismic.KeyTextField;

  /**
   * submenu_link field in *Menu → group_menu3*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.group_menu3[].submenu_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  submenu_link: prismic.LinkField;
}

/**
 * Item in *Menu → group_menu4*
 */
export interface MenuDocumentDataGroupMenu4Item {
  /**
   * submenu_name field in *Menu → group_menu4*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.group_menu4[].submenu_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  submenu_name: prismic.KeyTextField;

  /**
   * submenu_link field in *Menu → group_menu4*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.group_menu4[].submenu_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  submenu_link: prismic.LinkField;
}

/**
 * Item in *Menu → group_menu5*
 */
export interface MenuDocumentDataGroupMenu5Item {
  /**
   * submenu_name field in *Menu → group_menu5*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.group_menu5[].submenu_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  submenu_name: prismic.KeyTextField;

  /**
   * submenu_link field in *Menu → group_menu5*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.group_menu5[].submenu_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  submenu_link: prismic.LinkField;
}

/**
 * Item in *Menu → group_menu6*
 */
export interface MenuDocumentDataGroupMenu6Item {
  /**
   * submenu_name field in *Menu → group_menu6*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.group_menu6[].submenu_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  submenu_name: prismic.KeyTextField;

  /**
   * submenu_link field in *Menu → group_menu6*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.group_menu6[].submenu_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  submenu_link: prismic.LinkField;
}

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
  /**
   * menu_name field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_name
   * - **Tab**: Menu1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_name: prismic.KeyTextField;

  /**
   * group_menu field in *Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.group_menu[]
   * - **Tab**: Menu1
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  group_menu: prismic.GroupField<Simplify<MenuDocumentDataGroupMenuItem>> /**
   * menu_name2 field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_name2
   * - **Tab**: Menu2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  menu_name2: prismic.KeyTextField;

  /**
   * group_menu2 field in *Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.group_menu2[]
   * - **Tab**: Menu2
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  group_menu2: prismic.GroupField<Simplify<MenuDocumentDataGroupMenu2Item>> /**
   * menu_name3 field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_name3
   * - **Tab**: Menu3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  menu_name3: prismic.KeyTextField;

  /**
   * group_menu3 field in *Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.group_menu3[]
   * - **Tab**: Menu3
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  group_menu3: prismic.GroupField<Simplify<MenuDocumentDataGroupMenu3Item>> /**
   * menu_name4 field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_name4
   * - **Tab**: Menu4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  menu_name4: prismic.KeyTextField;

  /**
   * group_menu4 field in *Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.group_menu4[]
   * - **Tab**: Menu4
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  group_menu4: prismic.GroupField<Simplify<MenuDocumentDataGroupMenu4Item>> /**
   * menu_name5 field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_name5
   * - **Tab**: Menu5
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  menu_name5: prismic.KeyTextField;

  /**
   * group_menu5 field in *Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.group_menu5[]
   * - **Tab**: Menu5
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  group_menu5: prismic.GroupField<Simplify<MenuDocumentDataGroupMenu5Item>> /**
   * menu_name6 field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_name6
   * - **Tab**: Menu6
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  menu_name6: prismic.KeyTextField;

  /**
   * group_menu6 field in *Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.group_menu6[]
   * - **Tab**: Menu6
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  group_menu6: prismic.GroupField<Simplify<MenuDocumentDataGroupMenu6Item>>;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<MenuDocumentData>, "menu", Lang>;

type MockExamDocumentDataSlicesSlice =
  | TraningCourseListSlice
  | SpeakerSlice
  | TraningCourseSlice
  | TrainingAwardSlice
  | PortfolioSlice
  | IntroductionSlice
  | OpportunityListSlice
  | HeroSlice
  | ImageIconWithContentBottomSlice
  | ImageAndContentSideBySideSlice
  | HaveAProblemSlice
  | ExperienceSlice
  | BannerSectionSlice
  | CallToActionWithBannerSlice
  | BackgroundColorWithButtonLinkSlice
  | SpeakerWithContentSlice
  | PromotionAndPrivilegeSlice
  | ImageContentSlice
  | FeeSlice;

/**
 * Content for Mock Exam documents
 */
interface MockExamDocumentData {
  /**
   * Slice Zone field in *Mock Exam*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: mock_exam.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MockExamDocumentDataSlicesSlice> /**
   * Meta Description field in *Mock Exam*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: mock_exam.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Mock Exam*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mock_exam.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Mock Exam*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: mock_exam.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Mock Exam document from Prismic
 *
 * - **API ID**: `mock_exam`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MockExamDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MockExamDocumentData>,
    "mock_exam",
    Lang
  >;

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.TitleField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice = HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Parent field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.ContentRelationshipField<"page">;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type PrepareExamDocumentDataSlicesSlice =
  | ImageContentSlice
  | TraningCourseListSlice
  | PromotionAndPrivilegeSlice
  | TraningCourseSlice
  | IntroductionSlice
  | SpeakerWithContentSlice
  | SpeakerSlice
  | TrainingAwardSlice
  | ImageIconWithContentBottomSlice
  | OpportunityListSlice
  | PortfolioSlice
  | HeroSlice
  | HaveAProblemSlice
  | ImageAndContentSideBySideSlice
  | CallToActionWithBannerSlice
  | FeeSlice
  | BannerSectionSlice
  | FaqSlice
  | ExperienceSlice
  | BackgroundColorWithButtonLinkSlice;

/**
 * Content for Prepare Exam documents
 */
interface PrepareExamDocumentData {
  /**
   * Slice Zone field in *Prepare Exam*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: prepare_exam.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PrepareExamDocumentDataSlicesSlice> /**
   * Meta Description field in *Prepare Exam*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: prepare_exam.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Prepare Exam*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: prepare_exam.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Prepare Exam*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: prepare_exam.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Prepare Exam document from Prismic
 *
 * - **API ID**: `prepare_exam`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrepareExamDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PrepareExamDocumentData>,
    "prepare_exam",
    Lang
  >;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * image_logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.image_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_logo: prismic.ImageField<never>;

  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  siteTitle: prismic.TitleField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | AboutUsDocument
  | CurriculumDocument
  | ELearningDocument
  | FooterDocument
  | HomeDocument
  | MenuDocument
  | MockExamDocument
  | NavigationDocument
  | PageDocument
  | PrepareExamDocument
  | SettingsDocument;

/**
 * Primary content in *BackgroundColorWithButtonLink → Primary*
 */
export interface BackgroundColorWithButtonLinkSliceDefaultPrimary {
  /**
   * is_active field in *BackgroundColorWithButtonLink → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: background_color_with_button_link.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Primary content in *BackgroundColorWithButtonLink → Items*
 */
export interface BackgroundColorWithButtonLinkSliceDefaultItem {
  /**
   * button_title field in *BackgroundColorWithButtonLink → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: background_color_with_button_link.items[].button_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_title: prismic.KeyTextField;

  /**
   * button_description field in *BackgroundColorWithButtonLink → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: background_color_with_button_link.items[].button_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  button_description: prismic.RichTextField;

  /**
   * button_link field in *BackgroundColorWithButtonLink → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: background_color_with_button_link.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * button_color field in *BackgroundColorWithButtonLink → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: background_color_with_button_link.items[].button_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  button_color: prismic.ColorField;
}

/**
 * Default variation for BackgroundColorWithButtonLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BackgroundColorWithButtonLinkSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<BackgroundColorWithButtonLinkSliceDefaultPrimary>,
    Simplify<BackgroundColorWithButtonLinkSliceDefaultItem>
  >;

/**
 * Slice variation for *BackgroundColorWithButtonLink*
 */
type BackgroundColorWithButtonLinkSliceVariation =
  BackgroundColorWithButtonLinkSliceDefault;

/**
 * BackgroundColorWithButtonLink Shared Slice
 *
 * - **API ID**: `background_color_with_button_link`
 * - **Description**: BackgroundColorWithButtonLink
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BackgroundColorWithButtonLinkSlice = prismic.SharedSlice<
  "background_color_with_button_link",
  BackgroundColorWithButtonLinkSliceVariation
>;

/**
 * Primary content in *BannerSection → Primary*
 */
export interface BannerSectionSliceDefaultPrimary {
  /**
   * image_desktop field in *BannerSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_section.primary.image_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_desktop: prismic.ImageField<never>;

  /**
   * image_mobile field in *BannerSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_section.primary.image_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_mobile: prismic.ImageField<never>;

  /**
   * is_active field in *BannerSection → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: banner_section.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Default variation for BannerSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BannerSection*
 */
type BannerSectionSliceVariation = BannerSectionSliceDefault;

/**
 * BannerSection Shared Slice
 *
 * - **API ID**: `banner_section`
 * - **Description**: BannerSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSectionSlice = prismic.SharedSlice<
  "banner_section",
  BannerSectionSliceVariation
>;

/**
 * Primary content in *CallToActionWithBanner → Primary*
 */
export interface CallToActionWithBannerSliceDefaultPrimary {
  /**
   * title field in *CallToActionWithBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_with_banner.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * image_background_desktop field in *CallToActionWithBanner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_with_banner.primary.image_background_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_background_desktop: prismic.ImageField<never>;

  /**
   * image_background_mobile field in *CallToActionWithBanner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_with_banner.primary.image_background_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_background_mobile: prismic.ImageField<never>;

  /**
   * button_name field in *CallToActionWithBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_with_banner.primary.button_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_name: prismic.KeyTextField;

  /**
   * button_link field in *CallToActionWithBanner → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_with_banner.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for CallToActionWithBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionWithBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionWithBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallToActionWithBanner*
 */
type CallToActionWithBannerSliceVariation = CallToActionWithBannerSliceDefault;

/**
 * CallToActionWithBanner Shared Slice
 *
 * - **API ID**: `call_to_action_with_banner`
 * - **Description**: CallToActionWithBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionWithBannerSlice = prismic.SharedSlice<
  "call_to_action_with_banner",
  CallToActionWithBannerSliceVariation
>;

/**
 * Primary content in *Experience → Primary*
 */
export interface ExperienceSliceDefaultPrimary {
  /**
   * experience_title field in *Experience → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.primary.experience_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  experience_title: prismic.KeyTextField;

  /**
   * experience_subtitle field in *Experience → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.primary.experience_subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  experience_subtitle: prismic.KeyTextField;
}

/**
 * Primary content in *Experience → Items*
 */
export interface ExperienceSliceDefaultItem {
  /**
   * experience_image field in *Experience → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.items[].experience_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  experience_image: prismic.ImageField<never>;

  /**
   * experience_link_youtube field in *Experience → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.items[].experience_link_youtube
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  experience_link_youtube: prismic.LinkField;
}

/**
 * Default variation for Experience Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExperienceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExperienceSliceDefaultPrimary>,
  Simplify<ExperienceSliceDefaultItem>
>;

/**
 * Slice variation for *Experience*
 */
type ExperienceSliceVariation = ExperienceSliceDefault;

/**
 * Experience Shared Slice
 *
 * - **API ID**: `experience`
 * - **Description**: Experience
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExperienceSlice = prismic.SharedSlice<
  "experience",
  ExperienceSliceVariation
>;

/**
 * Primary content in *Faq → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * faq_title field in *Faq → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.faq_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  faq_title: prismic.KeyTextField;

  /**
   * is_active field in *Faq → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: faq.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Primary content in *Faq → Items*
 */
export interface FaqSliceDefaultItem {
  /**
   * faq_question field in *Faq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].faq_question
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  faq_question: prismic.RichTextField;

  /**
   * faq_answer field in *Faq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].faq_answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  faq_answer: prismic.RichTextField;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  Simplify<FaqSliceDefaultItem>
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *Fee → Primary*
 */
export interface FeeSliceDefaultPrimary {
  /**
   * title field in *Fee → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fee.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * theme_background field in *Fee → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: fee.primary.theme_background
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  theme_background: prismic.ColorField;

  /**
   * subtitle field in *Fee → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fee.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * small_course_name field in *Fee → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fee.primary.small_course_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  small_course_name: prismic.KeyTextField;

  /**
   * small_course_price field in *Fee → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fee.primary.small_course_price
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  small_course_price: prismic.KeyTextField;

  /**
   * small_course_condition field in *Fee → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fee.primary.small_course_condition
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  small_course_condition: prismic.KeyTextField;

  /**
   * is_active field in *Fee → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: fee.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Default variation for Fee Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Fee*
 */
type FeeSliceVariation = FeeSliceDefault;

/**
 * Fee Shared Slice
 *
 * - **API ID**: `fee`
 * - **Description**: Fee
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeeSlice = prismic.SharedSlice<"fee", FeeSliceVariation>;

/**
 * Primary content in *HaveAProblem → Primary*
 */
export interface HaveAProblemSliceDefaultPrimary {
  /**
   * have_a_problem_title field in *HaveAProblem → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: have_a_problem.primary.have_a_problem_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  have_a_problem_title: prismic.KeyTextField;

  /**
   * have_a_problem_image_desktop field in *HaveAProblem → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: have_a_problem.primary.have_a_problem_image_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  have_a_problem_image_desktop: prismic.ImageField<never>;

  /**
   * have_a_problem_image_mobile field in *HaveAProblem → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: have_a_problem.primary.have_a_problem_image_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  have_a_problem_image_mobile: prismic.ImageField<never>;

  /**
   * is_active field in *HaveAProblem → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: have_a_problem.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Primary content in *HaveAProblem → Items*
 */
export interface HaveAProblemSliceDefaultItem {
  /**
   * have_a_problem_image_icon field in *HaveAProblem → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: have_a_problem.items[].have_a_problem_image_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  have_a_problem_image_icon: prismic.ImageField<never>;

  /**
   * have_a_problem_description field in *HaveAProblem → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: have_a_problem.items[].have_a_problem_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  have_a_problem_description: prismic.RichTextField;
}

/**
 * Default variation for HaveAProblem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HaveAProblemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HaveAProblemSliceDefaultPrimary>,
  Simplify<HaveAProblemSliceDefaultItem>
>;

/**
 * Slice variation for *HaveAProblem*
 */
type HaveAProblemSliceVariation = HaveAProblemSliceDefault;

/**
 * HaveAProblem Shared Slice
 *
 * - **API ID**: `have_a_problem`
 * - **Description**: HaveAProblem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HaveAProblemSlice = prismic.SharedSlice<
  "have_a_problem",
  HaveAProblemSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * is_active field in *Hero → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceDefaultItem {
  /**
   * image_desktop field in *Hero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].image_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_desktop: prismic.ImageField<never>;

  /**
   * image_mobile field in *Hero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].image_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_mobile: prismic.ImageField<never>;

  /**
   * title field in *Hero → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * button_name field in *Hero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].button_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_name: prismic.KeyTextField;

  /**
   * button_link field in *Hero → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  Simplify<HeroSliceDefaultItem>
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImageAndContentSideBySide → Primary*
 */
export interface ImageAndContentSideBySideSliceDefaultPrimary {
  /**
   * theme_background field in *ImageAndContentSideBySide → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_content_side_by_side.primary.theme_background
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  theme_background: prismic.ColorField;

  /**
   * image_desktop field in *ImageAndContentSideBySide → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_content_side_by_side.primary.image_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_desktop: prismic.ImageField<never>;

  /**
   * image_mobile field in *ImageAndContentSideBySide → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_content_side_by_side.primary.image_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_mobile: prismic.ImageField<never>;

  /**
   * content field in *ImageAndContentSideBySide → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_content_side_by_side.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * is_active field in *ImageAndContentSideBySide → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image_and_content_side_by_side.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Default variation for ImageAndContentSideBySide Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndContentSideBySideSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<ImageAndContentSideBySideSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *ImageAndContentSideBySide*
 */
type ImageAndContentSideBySideSliceVariation =
  ImageAndContentSideBySideSliceDefault;

/**
 * ImageAndContentSideBySide Shared Slice
 *
 * - **API ID**: `image_and_content_side_by_side`
 * - **Description**: ImageAndContentSideBySide
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndContentSideBySideSlice = prismic.SharedSlice<
  "image_and_content_side_by_side",
  ImageAndContentSideBySideSliceVariation
>;

/**
 * Primary content in *ImageContent → Primary*
 */
export interface ImageContentSliceDefaultPrimary {
  /**
   * image_desktop field in *ImageContent → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content.primary.image_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_desktop: prismic.ImageField<never>;

  /**
   * image_mobile field in *ImageContent → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content.primary.image_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_mobile: prismic.ImageField<never>;

  /**
   * is_image_container field in *ImageContent → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_content.primary.is_image_container
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_image_container: prismic.BooleanField;

  /**
   * is_active field in *ImageContent → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_content.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;

  /**
   * image_link field in *ImageContent → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content.primary.image_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image_link: prismic.LinkField;
}

/**
 * Default variation for ImageContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageContent*
 */
type ImageContentSliceVariation = ImageContentSliceDefault;

/**
 * ImageContent Shared Slice
 *
 * - **API ID**: `image_content`
 * - **Description**: ImageContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageContentSlice = prismic.SharedSlice<
  "image_content",
  ImageContentSliceVariation
>;

/**
 * Primary content in *ImageIconWithContentBottom → Primary*
 */
export interface ImageIconWithContentBottomSliceDefaultPrimary {
  /**
   * button_name field in *ImageIconWithContentBottom → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_icon_with_content_bottom.primary.button_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_name: prismic.KeyTextField;

  /**
   * is_active field in *ImageIconWithContentBottom → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: image_icon_with_content_bottom.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;

  /**
   * button_link field in *ImageIconWithContentBottom → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_icon_with_content_bottom.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Primary content in *ImageIconWithContentBottom → Items*
 */
export interface ImageIconWithContentBottomSliceDefaultItem {
  /**
   * image_icon field in *ImageIconWithContentBottom → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_icon_with_content_bottom.items[].image_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_icon: prismic.ImageField<never>;

  /**
   * content_subject field in *ImageIconWithContentBottom → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_icon_with_content_bottom.items[].content_subject
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content_subject: prismic.RichTextField;
}

/**
 * Default variation for ImageIconWithContentBottom Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageIconWithContentBottomSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<ImageIconWithContentBottomSliceDefaultPrimary>,
    Simplify<ImageIconWithContentBottomSliceDefaultItem>
  >;

/**
 * Slice variation for *ImageIconWithContentBottom*
 */
type ImageIconWithContentBottomSliceVariation =
  ImageIconWithContentBottomSliceDefault;

/**
 * ImageIconWithContentBottom Shared Slice
 *
 * - **API ID**: `image_icon_with_content_bottom`
 * - **Description**: ImageIconWithContentBottom
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageIconWithContentBottomSlice = prismic.SharedSlice<
  "image_icon_with_content_bottom",
  ImageIconWithContentBottomSliceVariation
>;

/**
 * Primary content in *Introduction → Primary*
 */
export interface IntroductionSliceDefaultPrimary {
  /**
   * title field in *Introduction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: introduction.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * theme_background field in *Introduction → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: introduction.primary.theme_background
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  theme_background: prismic.ColorField;

  /**
   * is_active field in *Introduction → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: introduction.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;

  /**
   * image_icon field in *Introduction → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: introduction.primary.image_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_icon: prismic.ImageField<never>;
}

/**
 * Primary content in *Introduction → Items*
 */
export interface IntroductionSliceDefaultItem {
  /**
   * subject field in *Introduction → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: introduction.items[].subject
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subject: prismic.KeyTextField;
}

/**
 * Default variation for Introduction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroductionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IntroductionSliceDefaultPrimary>,
  Simplify<IntroductionSliceDefaultItem>
>;

/**
 * Slice variation for *Introduction*
 */
type IntroductionSliceVariation = IntroductionSliceDefault;

/**
 * Introduction Shared Slice
 *
 * - **API ID**: `introduction`
 * - **Description**: Introduction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IntroductionSlice = prismic.SharedSlice<
  "introduction",
  IntroductionSliceVariation
>;

/**
 * Primary content in *OpportunityList → Primary*
 */
export interface OpportunityListSliceDefaultPrimary {
  /**
   * opportunity_image_desktop field in *OpportunityList → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunity_list.primary.opportunity_image_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  opportunity_image_desktop: prismic.ImageField<never>;

  /**
   * opportunity_image_mobile field in *OpportunityList → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunity_list.primary.opportunity_image_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  opportunity_image_mobile: prismic.ImageField<never>;

  /**
   * oppportunity_title field in *OpportunityList → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunity_list.primary.oppportunity_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  oppportunity_title: prismic.RichTextField;

  /**
   * oppportunity_icon_list field in *OpportunityList → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunity_list.primary.oppportunity_icon_list
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  oppportunity_icon_list: prismic.ImageField<never>;

  /**
   * is_active field in *OpportunityList → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: opportunity_list.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Primary content in *OpportunityList → Items*
 */
export interface OpportunityListSliceDefaultItem {
  /**
   * opportunity_list_name field in *OpportunityList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: opportunity_list.items[].opportunity_list_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  opportunity_list_name: prismic.KeyTextField;
}

/**
 * Default variation for OpportunityList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OpportunityListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OpportunityListSliceDefaultPrimary>,
  Simplify<OpportunityListSliceDefaultItem>
>;

/**
 * Slice variation for *OpportunityList*
 */
type OpportunityListSliceVariation = OpportunityListSliceDefault;

/**
 * OpportunityList Shared Slice
 *
 * - **API ID**: `opportunity_list`
 * - **Description**: OpportunityList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OpportunityListSlice = prismic.SharedSlice<
  "opportunity_list",
  OpportunityListSliceVariation
>;

/**
 * Primary content in *Portfolio → Primary*
 */
export interface PortfolioSliceDefaultPrimary {
  /**
   * is_active field in *Portfolio → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: portfolio.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Primary content in *Portfolio → Items*
 */
export interface PortfolioSliceDefaultItem {
  /**
   * portfolio_image_desktop field in *Portfolio → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.items[].portfolio_image_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portfolio_image_desktop: prismic.ImageField<never>;

  /**
   * portfolio_image_mobile field in *Portfolio → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.items[].portfolio_image_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  portfolio_image_mobile: prismic.ImageField<never>;
}

/**
 * Default variation for Portfolio Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PortfolioSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PortfolioSliceDefaultPrimary>,
  Simplify<PortfolioSliceDefaultItem>
>;

/**
 * Slice variation for *Portfolio*
 */
type PortfolioSliceVariation = PortfolioSliceDefault;

/**
 * Portfolio Shared Slice
 *
 * - **API ID**: `portfolio`
 * - **Description**: Portfolio
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PortfolioSlice = prismic.SharedSlice<
  "portfolio",
  PortfolioSliceVariation
>;

/**
 * Primary content in *PromotionAndPrivilege → Primary*
 */
export interface PromotionAndPrivilegeSliceDefaultPrimary {
  /**
   * promotion_and_privilege_title field in *PromotionAndPrivilege → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promotion_and_privilege.primary.promotion_and_privilege_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  promotion_and_privilege_title: prismic.RichTextField;

  /**
   * promotion_image_banner_desktop field in *PromotionAndPrivilege → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: promotion_and_privilege.primary.promotion_image_banner_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  promotion_image_banner_desktop: prismic.ImageField<never>;

  /**
   * promotion_image_banner_mobile field in *PromotionAndPrivilege → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: promotion_and_privilege.primary.promotion_image_banner_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  promotion_image_banner_mobile: prismic.ImageField<never>;

  /**
   * is_active field in *PromotionAndPrivilege → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: promotion_and_privilege.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Primary content in *PromotionAndPrivilege → Items*
 */
export interface PromotionAndPrivilegeSliceDefaultItem {
  /**
   * promotion_and_privilege_desc field in *PromotionAndPrivilege → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: promotion_and_privilege.items[].promotion_and_privilege_desc
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  promotion_and_privilege_desc: prismic.RichTextField;
}

/**
 * Default variation for PromotionAndPrivilege Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PromotionAndPrivilegeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PromotionAndPrivilegeSliceDefaultPrimary>,
  Simplify<PromotionAndPrivilegeSliceDefaultItem>
>;

/**
 * Slice variation for *PromotionAndPrivilege*
 */
type PromotionAndPrivilegeSliceVariation = PromotionAndPrivilegeSliceDefault;

/**
 * PromotionAndPrivilege Shared Slice
 *
 * - **API ID**: `promotion_and_privilege`
 * - **Description**: PromotionAndPrivilege
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PromotionAndPrivilegeSlice = prismic.SharedSlice<
  "promotion_and_privilege",
  PromotionAndPrivilegeSliceVariation
>;

/**
 * Primary content in *Speaker → Primary*
 */
export interface SpeakerSliceDefaultPrimary {
  /**
   * title field in *Speaker → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * is_active field in *Speaker → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: speaker.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;

  /**
   * theme_color field in *Speaker → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker.primary.theme_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  theme_color: prismic.ColorField;
}

/**
 * Primary content in *Speaker → Items*
 */
export interface SpeakerSliceDefaultItem {
  /**
   * image_desktop field in *Speaker → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker.items[].image_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_desktop: prismic.ImageField<never>;

  /**
   * image_mobile field in *Speaker → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker.items[].image_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_mobile: prismic.ImageField<never>;

  /**
   * speaker_name field in *Speaker → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker.items[].speaker_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  speaker_name: prismic.KeyTextField;

  /**
   * speaker_description field in *Speaker → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker.items[].speaker_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  speaker_description: prismic.RichTextField;
}

/**
 * Default variation for Speaker Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpeakerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SpeakerSliceDefaultPrimary>,
  Simplify<SpeakerSliceDefaultItem>
>;

/**
 * Slice variation for *Speaker*
 */
type SpeakerSliceVariation = SpeakerSliceDefault;

/**
 * Speaker Shared Slice
 *
 * - **API ID**: `speaker`
 * - **Description**: Speaker
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpeakerSlice = prismic.SharedSlice<
  "speaker",
  SpeakerSliceVariation
>;

/**
 * Primary content in *SpeakerWithContent → Primary*
 */
export interface SpeakerWithContentSliceDefaultPrimary {
  /**
   * image_logo field in *SpeakerWithContent → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker_with_content.primary.image_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_logo: prismic.ImageField<never>;

  /**
   * title field in *SpeakerWithContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker_with_content.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *SpeakerWithContent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker_with_content.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * is_active field in *SpeakerWithContent → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: speaker_with_content.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Primary content in *SpeakerWithContent → Items*
 */
export interface SpeakerWithContentSliceDefaultItem {
  /**
   * speaker_image_desktop field in *SpeakerWithContent → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker_with_content.items[].speaker_image_desktop
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  speaker_image_desktop: prismic.ImageField<never>;

  /**
   * speaker_image_mobile field in *SpeakerWithContent → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker_with_content.items[].speaker_image_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  speaker_image_mobile: prismic.ImageField<never>;

  /**
   * speaker_name field in *SpeakerWithContent → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker_with_content.items[].speaker_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  speaker_name: prismic.KeyTextField;

  /**
   * speaker_detail field in *SpeakerWithContent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker_with_content.items[].speaker_detail
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  speaker_detail: prismic.RichTextField;
}

/**
 * Default variation for SpeakerWithContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpeakerWithContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SpeakerWithContentSliceDefaultPrimary>,
  Simplify<SpeakerWithContentSliceDefaultItem>
>;

/**
 * Slice variation for *SpeakerWithContent*
 */
type SpeakerWithContentSliceVariation = SpeakerWithContentSliceDefault;

/**
 * SpeakerWithContent Shared Slice
 *
 * - **API ID**: `speaker_with_content`
 * - **Description**: SpeakerWithContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpeakerWithContentSlice = prismic.SharedSlice<
  "speaker_with_content",
  SpeakerWithContentSliceVariation
>;

/**
 * Primary content in *TrainingAward → Primary*
 */
export interface TrainingAwardSliceDefaultPrimary {
  /**
   * training_award_highlight field in *TrainingAward → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: training_award.primary.training_award_highlight
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  training_award_highlight: prismic.KeyTextField;

  /**
   * training_award_title field in *TrainingAward → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: training_award.primary.training_award_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  training_award_title: prismic.KeyTextField;

  /**
   * training_award_subtitle field in *TrainingAward → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: training_award.primary.training_award_subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  training_award_subtitle: prismic.RichTextField;

  /**
   * is_active field in *TrainingAward → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: training_award.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Primary content in *TrainingAward → Items*
 */
export interface TrainingAwardSliceDefaultItem {
  /**
   * training_award_step field in *TrainingAward → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: training_award.items[].training_award_step
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  training_award_step: prismic.KeyTextField;

  /**
   * training_award_step_detail field in *TrainingAward → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: training_award.items[].training_award_step_detail
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  training_award_step_detail: prismic.KeyTextField;
}

/**
 * Default variation for TrainingAward Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TrainingAwardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TrainingAwardSliceDefaultPrimary>,
  Simplify<TrainingAwardSliceDefaultItem>
>;

/**
 * Slice variation for *TrainingAward*
 */
type TrainingAwardSliceVariation = TrainingAwardSliceDefault;

/**
 * TrainingAward Shared Slice
 *
 * - **API ID**: `training_award`
 * - **Description**: TrainingAward
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TrainingAwardSlice = prismic.SharedSlice<
  "training_award",
  TrainingAwardSliceVariation
>;

/**
 * Primary content in *TraningCourseCard → Primary*
 */
export interface TraningCourseSliceDefaultPrimary {
  /**
   * title_course field in *TraningCourseCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course.primary.title_course
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_course: prismic.KeyTextField;

  /**
   * subtitle_course field in *TraningCourseCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course.primary.subtitle_course
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle_course: prismic.KeyTextField;

  /**
   * button_all_name_course field in *TraningCourseCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course.primary.button_all_name_course
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_all_name_course: prismic.KeyTextField;

  /**
   * button_all_link_course field in *TraningCourseCard → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course.primary.button_all_link_course
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_all_link_course: prismic.LinkField;

  /**
   * is_active field in *TraningCourseCard → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: traning_course.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Primary content in *TraningCourseCard → Items*
 */
export interface TraningCourseSliceDefaultItem {
  /**
   * course_name field in *TraningCourseCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title Course
   * - **API ID Path**: traning_course.items[].course_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  course_name: prismic.KeyTextField;

  /**
   * course_description field in *TraningCourseCard → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description Course
   * - **API ID Path**: traning_course.items[].course_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  course_description: prismic.RichTextField;

  /**
   * course_image_icon field in *TraningCourseCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course.items[].course_image_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  course_image_icon: prismic.ImageField<never>;

  /**
   * course_button_name field in *TraningCourseCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Button name
   * - **API ID Path**: traning_course.items[].course_button_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  course_button_name: prismic.KeyTextField;

  /**
   * course_button_link field in *TraningCourseCard → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Button Link
   * - **API ID Path**: traning_course.items[].course_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  course_button_link: prismic.LinkField;
}

/**
 * Default variation for TraningCourseCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TraningCourseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TraningCourseSliceDefaultPrimary>,
  Simplify<TraningCourseSliceDefaultItem>
>;

/**
 * Slice variation for *TraningCourseCard*
 */
type TraningCourseSliceVariation = TraningCourseSliceDefault;

/**
 * TraningCourseCard Shared Slice
 *
 * - **API ID**: `traning_course`
 * - **Description**: TraningCourse
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TraningCourseSlice = prismic.SharedSlice<
  "traning_course",
  TraningCourseSliceVariation
>;

/**
 * Primary content in *TraningCourseList → Primary*
 */
export interface TraningCourseListSliceDefaultPrimary {
  /**
   * title_course field in *TraningCourseList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course_list.primary.title_course
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_course: prismic.KeyTextField;

  /**
   * subtitle_course field in *TraningCourseList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course_list.primary.subtitle_course
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle_course: prismic.KeyTextField;

  /**
   * button_all_name_course field in *TraningCourseList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course_list.primary.button_all_name_course
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_all_name_course: prismic.KeyTextField;

  /**
   * button_all_name_link field in *TraningCourseList → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course_list.primary.button_all_name_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_all_name_link: prismic.LinkField;

  /**
   * is_active field in *TraningCourseList → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: traning_course_list.primary.is_active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_active: prismic.BooleanField;
}

/**
 * Primary content in *TraningCourseList → Items*
 */
export interface TraningCourseListSliceDefaultItem {
  /**
   * course_name field in *TraningCourseList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course_list.items[].course_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  course_name: prismic.KeyTextField;

  /**
   * course_description field in *TraningCourseList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course_list.items[].course_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  course_description: prismic.KeyTextField;

  /**
   * course_sub_description field in *TraningCourseList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course_list.items[].course_sub_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  course_sub_description: prismic.KeyTextField;

  /**
   * course_button_name field in *TraningCourseList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course_list.items[].course_button_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  course_button_name: prismic.KeyTextField;

  /**
   * course_button_link field in *TraningCourseList → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: traning_course_list.items[].course_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  course_button_link: prismic.LinkField;
}

/**
 * Default variation for TraningCourseList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TraningCourseListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TraningCourseListSliceDefaultPrimary>,
  Simplify<TraningCourseListSliceDefaultItem>
>;

/**
 * Slice variation for *TraningCourseList*
 */
type TraningCourseListSliceVariation = TraningCourseListSliceDefault;

/**
 * TraningCourseList Shared Slice
 *
 * - **API ID**: `traning_course_list`
 * - **Description**: TraningCourseList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TraningCourseListSlice = prismic.SharedSlice<
  "traning_course_list",
  TraningCourseListSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutUsDocument,
      AboutUsDocumentData,
      AboutUsDocumentDataSlicesSlice,
      CurriculumDocument,
      CurriculumDocumentData,
      CurriculumDocumentDataSlicesSlice,
      ELearningDocument,
      ELearningDocumentData,
      ELearningDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataOurServicesItem,
      FooterDocumentDataSocialMediaListItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      MenuDocument,
      MenuDocumentData,
      MenuDocumentDataGroupMenuItem,
      MenuDocumentDataGroupMenu2Item,
      MenuDocumentDataGroupMenu3Item,
      MenuDocumentDataGroupMenu4Item,
      MenuDocumentDataGroupMenu5Item,
      MenuDocumentDataGroupMenu6Item,
      MockExamDocument,
      MockExamDocumentData,
      MockExamDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PrepareExamDocument,
      PrepareExamDocumentData,
      PrepareExamDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      BackgroundColorWithButtonLinkSlice,
      BackgroundColorWithButtonLinkSliceDefaultPrimary,
      BackgroundColorWithButtonLinkSliceDefaultItem,
      BackgroundColorWithButtonLinkSliceVariation,
      BackgroundColorWithButtonLinkSliceDefault,
      BannerSectionSlice,
      BannerSectionSliceDefaultPrimary,
      BannerSectionSliceVariation,
      BannerSectionSliceDefault,
      CallToActionWithBannerSlice,
      CallToActionWithBannerSliceDefaultPrimary,
      CallToActionWithBannerSliceVariation,
      CallToActionWithBannerSliceDefault,
      ExperienceSlice,
      ExperienceSliceDefaultPrimary,
      ExperienceSliceDefaultItem,
      ExperienceSliceVariation,
      ExperienceSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimary,
      FaqSliceDefaultItem,
      FaqSliceVariation,
      FaqSliceDefault,
      FeeSlice,
      FeeSliceDefaultPrimary,
      FeeSliceVariation,
      FeeSliceDefault,
      HaveAProblemSlice,
      HaveAProblemSliceDefaultPrimary,
      HaveAProblemSliceDefaultItem,
      HaveAProblemSliceVariation,
      HaveAProblemSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefaultItem,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageAndContentSideBySideSlice,
      ImageAndContentSideBySideSliceDefaultPrimary,
      ImageAndContentSideBySideSliceVariation,
      ImageAndContentSideBySideSliceDefault,
      ImageContentSlice,
      ImageContentSliceDefaultPrimary,
      ImageContentSliceVariation,
      ImageContentSliceDefault,
      ImageIconWithContentBottomSlice,
      ImageIconWithContentBottomSliceDefaultPrimary,
      ImageIconWithContentBottomSliceDefaultItem,
      ImageIconWithContentBottomSliceVariation,
      ImageIconWithContentBottomSliceDefault,
      IntroductionSlice,
      IntroductionSliceDefaultPrimary,
      IntroductionSliceDefaultItem,
      IntroductionSliceVariation,
      IntroductionSliceDefault,
      OpportunityListSlice,
      OpportunityListSliceDefaultPrimary,
      OpportunityListSliceDefaultItem,
      OpportunityListSliceVariation,
      OpportunityListSliceDefault,
      PortfolioSlice,
      PortfolioSliceDefaultPrimary,
      PortfolioSliceDefaultItem,
      PortfolioSliceVariation,
      PortfolioSliceDefault,
      PromotionAndPrivilegeSlice,
      PromotionAndPrivilegeSliceDefaultPrimary,
      PromotionAndPrivilegeSliceDefaultItem,
      PromotionAndPrivilegeSliceVariation,
      PromotionAndPrivilegeSliceDefault,
      SpeakerSlice,
      SpeakerSliceDefaultPrimary,
      SpeakerSliceDefaultItem,
      SpeakerSliceVariation,
      SpeakerSliceDefault,
      SpeakerWithContentSlice,
      SpeakerWithContentSliceDefaultPrimary,
      SpeakerWithContentSliceDefaultItem,
      SpeakerWithContentSliceVariation,
      SpeakerWithContentSliceDefault,
      TrainingAwardSlice,
      TrainingAwardSliceDefaultPrimary,
      TrainingAwardSliceDefaultItem,
      TrainingAwardSliceVariation,
      TrainingAwardSliceDefault,
      TraningCourseSlice,
      TraningCourseSliceDefaultPrimary,
      TraningCourseSliceDefaultItem,
      TraningCourseSliceVariation,
      TraningCourseSliceDefault,
      TraningCourseListSlice,
      TraningCourseListSliceDefaultPrimary,
      TraningCourseListSliceDefaultItem,
      TraningCourseListSliceVariation,
      TraningCourseListSliceDefault,
    };
  }
}
