// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  background_color_with_button_link: dynamic(
    () => import("./BackgroundColorWithButtonLink"),
  ),
  banner_section: dynamic(() => import("./BannerSection")),
  call_to_action_with_banner: dynamic(() => import("./CallToActionWithBanner")),
  have_a_problem: dynamic(() => import("./HaveAProblem")),
  hero: dynamic(() => import("./Hero")),
  image_icon_with_content_bottom: dynamic(
    () => import("./ImageIconWithContentBottom"),
  ),
  opportunity_list: dynamic(() => import("./OpportunityList")),
  promotion_and_privilege: dynamic(() => import("./PromotionAndPrivilege")),
  text: dynamic(() => import("./Text")),
  training_award: dynamic(() => import("./TrainingAward")),
  traning_course: dynamic(() => import("./TraningCourseCard")),
  traning_course_list: dynamic(() => import("./TraningCourseList")),
};
